### ISSUE TITLE
Bump the dependency lib's version

### ISSUE THREAD

**Issue by Aisuko** [SkywardAI/kimchima#109]
```
ec2-user@ip-10-110-145-52:~/workspace/chat-backend$ docker logs -f 88a639cf46c9
DB Connection --- Establishing . . .
DB Connection --- Successfully Established!
INFO:     Will watch for changes in these directories: ['/app']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [1] using StatReload
2024-06-29 06:37:22.524 | INFO     | src.repository.vector_database:__init__:15 - Vector Database --- Connected to Milvus.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/lib/python3.11/multiprocessing/spawn.py", line 135, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
  File "/usr/local/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/app/src/main.py", line 6, in <module>
    from src.api.endpoints import router as api_endpoint_router
  File "/app/src/api/endpoints.py", line 4, in <module>
    from src.api.routes.ai_model import router as ai_model_router
  File "/app/src/api/routes/ai_model.py", line 8, in <module>
    from src.repository.rag.chat import RAGChatModelRepository
  File "/app/src/repository/rag/chat.py", line 12, in <module>
    from src.repository.conversation import ConversationWithSession, conversations
  File "/app/src/repository/conversation.py", line 6, in <module>
    from kimchima.pkg import PipelinesFactory
  File "/usr/local/lib/python3.11/site-packages/kimchima/__init__.py", line 16, in <module>
    from kimchima.pkg import (
  File "/usr/local/lib/python3.11/site-packages/kimchima/pkg/__init__.py", line 19, in <module>
    from .model_factory import ModelFactory
  File "/usr/local/lib/python3.11/site-packages/kimchima/pkg/model_factory.py", line 20, in <module>
    from transformers import (
  File "/usr/local/lib/python3.11/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/usr/local/lib/python3.11/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/usr/local/lib/python3.11/site-packages/transformers/utils/__init__.py", line 33, in <module>
    from .generic import (
  File "/usr/local/lib/python3.11/site-packages/transformers/utils/generic.py", line 465, in <module>
    import torch.utils._pytree as _torch_pytree
  File "/usr/local/lib/python3.11/site-packages/torch/__init__.py", line 1477, in <module>
    from .functional import *  # noqa: F403
  File "/usr/local/lib/python3.11/site-packages/torch/functional.py", line 9, in <module>
    import torch.nn.functional as F
  File "/usr/local/lib/python3.11/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/usr/local/lib/python3.11/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
INFO:     Started server process [9]
INFO:     Waiting for application startup.
2024-06-29 06:37:24.652 | INFO     | src.repository.events:initialize_db_connection:42 - Database Connection --- Establishing . . .
2024-06-29 06:37:24.682 | INFO     | src.repository.events:inspect_db_server_on_connection:20 - New DB API Connection ---
 <AdaptedConnection <asyncpg.connection.Connection object at 0x7f28207236a0>>
2024-06-29 06:37:24.682 | INFO     | src.repository.events:inspect_db_server_on_connection:21 - Connection Record ---
 <sqlalchemy.pool.base._ConnectionRecord object at 0x7f2820748d00>
2024-06-29 06:37:24.682 | INFO     | src.repository.events:initialize_db_tables:33 - Database Table Creation --- Initializing . . .
2024-06-29 06:37:24.738 | INFO     | src.repository.events:initialize_db_tables:38 - Database Table Creation --- Successfully Initialized!
2024-06-29 06:37:24.741 | INFO     | src.repository.events:initialize_db_connection:49 - Database Connection --- Successfully Established!
2024-06-29 06:37:24.741 | INFO     | src.repository.events:initialize_vectordb_collection:54 - Vector Database Connection --- Establishing . . .
2024-06-29 06:37:56.863 | INFO     | src.repository.vector_database:create_collection:47 - Vector Database --- Milvus: collection default_collection created
2024-06-29 06:37:56.864 | INFO     | src.repository.events:initialize_vectordb_collection:72 - Vector Database Connection --- Successfully Established!
2024-06-29 06:37:56.864 | INFO     | src.repository.events:initialize_inference_client:93 - Inference Client --- Waiting for Initialization . . .
2024-06-29 06:37:56.887 | INFO     | src.repository.events:initialize_inference_client:98 - Inference Client --- Successfully Initialized!
INFO:     Application startup complete.
```

**Comment by Aisuko** [comment]
https://github.com/pytorch/pytorch/issues/122056

**Comment by Aisuko** [comment]
fix this issue by bumping PyTorch
